spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pets}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.SQL: DEBUG
    org.apache.http: DEBUG
    httpclient.wire: DEBUG