server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:Dev}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  jackson:
    mapper.ACCEPT_CASE_INSENSITIVE_ENUMS: true