spring:
  datasource:
    url: ${vcap.services.postgreSQL-DB.credentials.url}
    username: ${vcap.services.postgreSQL-DB.credentials.username}
    password: ${vcap.services.postgreSQL-DB.credentials.password}
    driver-class-name: org.postgresql.Driver
#    driver-class-name: org.h2.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    org.hibernate.SQL: debug
